In [1]:
import pandas as pd

path = "US_Accidents_March23.csv"
df = pd.read_csv(path)

# pd.set_option('display.max_rows', None)
# df
# df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [2]:
list(df["Weather_Condition"].unique())

['Light Rain',
 'Overcast',
 'Mostly Cloudy',
 'Rain',
 'Light Snow',
 'Haze',
 'Scattered Clouds',
 'Partly Cloudy',
 'Clear',
 'Snow',
 'Light Freezing Drizzle',
 'Light Drizzle',
 'Fog',
 'Shallow Fog',
 'Heavy Rain',
 'Light Freezing Rain',
 'Cloudy',
 'Drizzle',
 nan,
 'Light Rain Showers',
 'Mist',
 'Smoke',
 'Patches of Fog',
 'Light Freezing Fog',
 'Light Haze',
 'Light Thunderstorms and Rain',
 'Thunderstorms and Rain',
 'Fair',
 'Volcanic Ash',
 'Blowing Sand',
 'Blowing Dust / Windy',
 'Widespread Dust',
 'Fair / Windy',
 'Rain Showers',
 'Mostly Cloudy / Windy',
 'Light Rain / Windy',
 'Hail',
 'Heavy Drizzle',
 'Showers in the Vicinity',
 'Thunderstorm',
 'Light Rain Shower',
 'Light Rain with Thunder',
 'Partly Cloudy / Windy',
 'Thunder in the Vicinity',
 'T-Storm',
 'Heavy Thunderstorms and Rain',
 'Thunder',
 'Heavy T-Storm',
 'Funnel Cloud',
 'Heavy T-Storm / Windy',
 'Blowing Snow',
 'Light Thunderstorms and Snow',
 'Heavy Snow',
 'Low Drifting Snow',
 'Light Ice Pellets',
 'Ice Pellets',
 'Squalls',
 'N/A Precipitation',
 'Cloudy / Windy',
 'Light Fog',
 'Sand',
 'Snow Grains',
 'Snow Showers',
 'Heavy Thunderstorms and Snow',
 'Rain / Windy',
 'Heavy Rain / Windy',
 'Heavy Ice Pellets',
 'Light Snow / Windy',
 'Heavy Freezing Rain',
 'Small Hail',
 'Heavy Rain Showers',
 'Thunder / Windy',
 'Drizzle and Fog',
 'T-Storm / Windy',
 'Blowing Dust',
 'Smoke / Windy',
 'Haze / Windy',
 'Tornado',
 'Light Drizzle / Windy',
 'Widespread Dust / Windy',
 'Wintry Mix',
 'Wintry Mix / Windy',
 'Light Snow with Thunder',
 'Fog / Windy',
 'Snow and Thunder',
 'Light Snow Shower',
 'Sleet',
 'Light Snow and Sleet',
 'Snow / Windy',
 'Rain Shower',
 'Snow and Sleet',
 'Light Sleet',
 'Heavy Snow / Windy',
 'Freezing Drizzle',
 'Light Freezing Rain / Windy',
 'Thunder / Wintry Mix',
 'Blowing Snow / Windy',
 'Freezing Rain',
 'Light Snow and Sleet / Windy',
 'Snow and Sleet / Windy',
 'Sleet / Windy',
 'Heavy Freezing Rain / Windy',
 'Squalls / Windy',
 'Light Rain Shower / Windy',
 'Snow and Thunder / Windy',
 'Light Sleet / Windy',
 'Sand / Dust Whirlwinds',
 'Mist / Windy',
 'Drizzle / Windy',
 'Duststorm',
 'Sand / Dust Whirls Nearby',
 'Thunder and Hail',
 'Heavy Sleet',
 'Freezing Rain / Windy',
 'Light Snow Shower / Windy',
 'Partial Fog',
 'Thunder / Wintry Mix / Windy',
 'Patches of Fog / Windy',
 'Rain and Sleet',
 'Light Snow Grains',
 'Partial Fog / Windy',
 'Sand / Dust Whirlwinds / Windy',
 'Heavy Snow with Thunder',
 'Light Snow Showers',
 'Heavy Blowing Snow',
 'Light Hail',
 'Heavy Smoke',
 'Heavy Thunderstorms with Small Hail',
 'Light Thunderstorm',
 'Heavy Freezing Drizzle',
 'Light Blowing Snow',
 'Thunderstorms and Snow',
 'Dust Whirls',
 'Rain Shower / Windy',
 'Sleet and Thunder',
 'Heavy Sleet and Thunder',
 'Drifting Snow / Windy',
 'Shallow Fog / Windy',
 'Thunder and Hail / Windy',
 'Heavy Sleet / Windy',
 'Sand / Windy',
 'Heavy Rain Shower / Windy',
 'Blowing Snow Nearby',
 'Heavy Rain Shower',
 'Drifting Snow']

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   object
 13  County                 object
 14  State                  object
 15  Zipcode                object
 16  Country                object
 17  Timezone               object
 18  Airport_Code           object
 19  Weather_Timestamp      object
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         object
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      object
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         object
 43  Civil_Twilight         object
 44  Nautical_Twilight      object
 45  Astronomical_Twilight  object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 2.0+ GB

<!-- Source, End_Lat, End_Lng, Distance(mi), Country, Weather_Timestamp, Civil_Twilight, Astronomical_Twilight -->

In [4]:
df_filtered = df.copy()
del df_filtered["Source"]
del df_filtered["End_Lat"]
del df_filtered["End_Lng"]
del df_filtered["Distance(mi)"]
del df_filtered["Country"]
del df_filtered["Weather_Timestamp"]
del df_filtered["Civil_Twilight"]
del df_filtered["Astronomical_Twilight"]
del df_filtered["Nautical_Twilight"]
# df_filtered

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Description,Street,City,County,...,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset
0,A-1,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,Right lane blocked due to accident on I-70 Eas...,I-70 E,Dayton,Montgomery,...,False,False,False,False,False,False,False,False,False,Night
1,A-2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,Accident on Brice Rd at Tussing Rd. Expect del...,Brice Rd,Reynoldsburg,Franklin,...,False,False,False,False,False,False,False,False,False,Night
2,A-3,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,Williamsburg,Clermont,...,False,False,False,False,False,False,False,True,False,Night
3,A-4,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,Dayton,Montgomery,...,False,False,False,False,False,False,False,False,False,Night
4,A-5,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,Dayton,Montgomery,...,False,False,False,False,False,False,False,True,False,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728389,A-7777757,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,At Market St - Accident.,Pomona Fwy E,Riverside,Riverside,...,False,False,False,False,False,False,False,False,False,Day
7728390,A-7777758,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,At Camino Del Rio/Mission Center Rd - Accident.,I-8 W,San Diego,San Diego,...,False,False,False,False,False,False,False,False,False,Day
7728391,A-7777759,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,At Glassell St/Grand Ave - Accident. in the ri...,Garden Grove Fwy,Orange,Orange,...,True,False,False,False,False,False,False,False,False,Day
7728392,A-7777760,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,San Diego Fwy S,Culver City,Los Angeles,...,False,False,False,False,False,False,False,False,False,Day
7728393,A-7777761,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,At Highland Ave/Arden Ave - Accident.,CA-210 W,Highland,San Bernardino,...,False,False,False,False,False,False,False,False,False,Day

In [5]:
df_filtered['Start_Time'] = pd.to_datetime(df_filtered['Start_Time'], format ='mixed')
df_filtered['End_Time'] = pd.to_datetime(df_filtered['End_Time'], format ='mixed')

In [6]:
df_filtered.loc[:, 'Year'] = df_filtered['Start_Time'].dt.year
df_filtered.loc[:, 'Month'] = df_filtered['Start_Time'].dt.month
df_filtered.loc[:, 'Day_Name'] = df_filtered['Start_Time'].dt.day_name()

In [ ]:
# df_filtered.head()

In [8]:
df_2016 = df_filtered[df_filtered["Year"] == 2016]
df_2017 = df_filtered[df_filtered["Year"] == 2017]
df_2018 = df_filtered[df_filtered["Year"] == 2018]
df_2019 = df_filtered[df_filtered["Year"] == 2019]
df_2020 = df_filtered[df_filtered["Year"] == 2020]
df_2021 = df_filtered[df_filtered["Year"] == 2021]
df_2022 = df_filtered[df_filtered["Year"] == 2022]
df_2023 = df_filtered[df_filtered["Year"] == 2023]

In [20]:
df_2016.to_csv('Data/df_2016.csv', index=False)
df_2017.to_csv('Data/df_2017.csv', index=False)
df_2018.to_csv('Data/df_2018.csv', index=False)
df_2019.to_csv('Data/df_2019.csv', index=False)
df_2020.to_csv('Data/df_2020.csv', index=False)
df_2021.to_csv('Data/df_2021.csv', index=False)
df_2022.to_csv('Data/df_2022.csv', index=False)
df_2023.to_csv('Data/df_2023.csv', index=False)